blank_issues_enabled: false
contact_links:
  - name: Spike's Discussions
    url: https://github.com/FIRECATinBLACK/Spikecat/discussions
    about: The right place for all your questions, suggestions etc.